export const SEND_ITEM_TO_STORE = "SEND_ITEM_TO_STORE";
export const FORM_STATUS = "FORM_STATUS";
export const PUSH_ITEM_RECEIVED_TO_STORE = "PUSH_ITEM_RECEIVED_TO_STORE";
export const UPDATE_ITEM_FROM_STORE_TO_FIREBASE =
    "UPDATE_ITEM_FROM_STORE_TO_FIREBASE";
export const DELETE_ITEM = "DELETE_ITEM";
export const HANDLE_IS_ADD = "HANDLE_IS_ADD";
export const ALERT_STATUS_HANDLER_ON = "ALERT_STATUS_HANDLER_ON";
export const ALERT_STATUS_HANDLER_OFF = "ALERT_STATUS_HANDLER_OFF";
